Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/xenial64"

  (1..2).each do |i|
  config.vm.define "node-#{i}" do |node|
    node.vm.network "private_network", ip: "192.168.33.1#{i}"
    node.vm.hostname = "node-#{i}"
    node.vm.provider "virtualbox" do |vb|
      vb.gui = false
      vb.memory = "1024"
    end
    node.vm.provision "shell", path: "provision.sh" 
  end
end
end
