Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/xenial64"

  (1..2).each do |i|
  config.vm.define "node-#{i}" do |node|
    node.vm.network "private_network", ip: "192.168.33.1#{i}"
    node.vm.network "forwarded_port", guest: 8001, host: 8001
    node.vm.network "forwarded_port", guest: 8080, host: 8080
    node.vm.network "forwarded_port", guest: 6443, host: 6443
    node.vm.network "forwarded_port", guest: 10250, host: 10250
    node.vm.network "forwarded_port", guest: 443, host: 443
    node.vm.provider "virtualbox" do |vb|
      vb.gui = false
      vb.memory = "1024"
    end
    node.vm.provision "shell", path: "provision.sh" 
  end
end
end
